package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"cds-graphql-poc/graph"
	"cds-graphql-poc/graph/model"
	"cds-graphql-poc/graph/utils"
	"context"
	"fmt"
	"strconv"
)

// CompaniesByIDOrg is the resolver for the companiesByIdOrg field.
func (r *queryResolver) CompaniesByIDOrg(ctx context.Context, ids []*string) ([]*model.Company, error) {
	intIds := []int{}
	for _, id := range ids {
		newId, err := strconv.Atoi(*id)

		if err != nil {
			return nil, fmt.Errorf("error converting id to int: %v", err)
		}

		intIds = append(intIds, newId)
	}

	profiles, err := r.ProfileServiceClient.GetProfilesById(ctx, intIds)

	if err != nil {
		return nil, fmt.Errorf("error getting profiles by id: %v", err)
	}

	companies := []*model.Company{}

	for _, profile := range profiles {

		profileURL, err := utils.GenerateProfileURL(profile.IdCbiEntity)

		if err != nil {
			return nil, fmt.Errorf("error generating profile URL: %v", err)
		}

		location := &model.CompanyLocation{}
		if profile.Address != nil {
			location = &model.CompanyLocation{
				Country: profile.Address.Country,
				State:   profile.Address.State,
				City:    profile.Address.City,
			}

		}

		companies = append(companies, &model.Company{
			ID:         strconv.Itoa(profile.IdCbiEntity),
			OrgID:      int32(profile.IdCbiEntity),
			InvestorID: int32(profile.IdInvestor),
			CompanyID:  int32(profile.IdCompany),
			Name:       profile.Name,
			Status:     profile.Status,
			Website:    profile.Url,
			ProfileURL: profileURL,
			Location:   location,
		})
	}

	return companies, nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
